### ISSUE TITLE
How can I solve this error?

### ISSUE THREAD

**Issue by 165412152** [NX-AI/vision-lstm#8]
assert all(x.size(i + 2) % self.patch_size[i] == 0 for i in range(self.ndim)), \
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by BenediktAlkin** [comment]
there is probably something wrong with your input. by default input_shape=(3, 224, 224) expects rgb images (so a 4D tensor with the first dimension being the batch size). since you get an indexerror I'd assume that maybe you are missing the channel dimension or the batch dimension.

otherwise check that your actual input x matches the input_shape you pass to the VisionLSTM and that your input is divisible by the patch size

**Comment by 165412152** [comment]
def __init__(
            self,
            dim=192,
            input_shape=(3, 224, 224),
            patch_size=16,
            depth=12,
            output_shape=(1000,),
            mode="classifier",
            pooling="bilateral_flatten",
            drop_path_rate=0.0,
            drop_path_decay=False,
            stride=None,
            legacy_norm=False,
            conv_kind="2d",
            conv_kernel_size=3,
            proj_bias=True,
            norm_bias=True,
    ):

if __name__ == '__main__':
    x = torch.randn(3, 224, 224).cuda()
    model = VisionLSTM2().cuda()
    output = model(x)
    
  I didn't modify any code, I just wrote a test data

**Comment by 165412152** [comment]
Thanks for reminding me, I should enter the data of [B,C,W,H]
